# Proxy 
[[redirects]]
  from = "/api/airtable"
  to = "https://api.airtable.com/v0/appDkNR2MuAvgiOAS"
  status = 200

  [redirects.headers]
    Authorization = "Bearer $AIRTABLE_API_KEY"

[[redirects]]
  from = "https:/registry.campbellkrakow.com/"
  to = "https://www.zola.com/registry/campbellkrakow"
  status = 301

[[headers]]
  # Define which paths this specific [[headers]] block will cover.
  for = "/*"
    [headers.values]
    Access-Control-Allow-Origin = "*"